//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjmedia_format_id
{
    PJMEDIA_FORMAT_L16 = 0,
    PJMEDIA_FORMAT_PCM = PJMEDIA_FORMAT_L16,
    PJMEDIA_FORMAT_PCMA = ((((int)'W' << 24) | ((int)'A' << 16)) | ((int)'L' << 8)) | (int)'A',
    PJMEDIA_FORMAT_ALAW = PJMEDIA_FORMAT_PCMA,
    PJMEDIA_FORMAT_PCMU = ((((int)'W' << 24) | ((int)'A' << 16)) | ((int)'L' << 8)) | (int)'u',
    PJMEDIA_FORMAT_ULAW = PJMEDIA_FORMAT_PCMU,
    PJMEDIA_FORMAT_AMR = ((((int)'R' << 24) | ((int)'M' << 16)) | ((int)'A' << 8)) | ' ',
    PJMEDIA_FORMAT_G729 = ((((int)'9' << 24) | ((int)'2' << 16)) | ((int)'7' << 8)) | (int)'G',
    PJMEDIA_FORMAT_ILBC = ((((int)'C' << 24) | ((int)'B' << 16)) | ((int)'L' << 8)) | (int)'I',
    PJMEDIA_FORMAT_RGB24 = ((((int)'3' << 24) | ((int)'B' << 16)) | ((int)'G' << 8)) | (int)'R',
    PJMEDIA_FORMAT_RGBA = ((((int)'A' << 24) | ((int)'B' << 16)) | ((int)'G' << 8)) | (int)'R',
    PJMEDIA_FORMAT_BGRA = ((((int)'A' << 24) | ((int)'R' << 16)) | ((int)'G' << 8)) | (int)'B',
    PJMEDIA_FORMAT_RGB32 = PJMEDIA_FORMAT_RGBA,
    PJMEDIA_FORMAT_DIB = ((((int)' ' << 24) | ((int)'B' << 16)) | ((int)'I' << 8)) | (int)'D',
    PJMEDIA_FORMAT_GBRP = ((((int)'P' << 24) | ((int)'R' << 16)) | ((int)'B' << 8)) | (int)'G',
    PJMEDIA_FORMAT_AYUV = ((((int)'V' << 24) | ((int)'U' << 16)) | ((int)'Y' << 8)) | (int)'A',
    PJMEDIA_FORMAT_YUY2 = ((((int)'2' << 24) | ((int)'Y' << 16)) | ((int)'U' << 8)) | (int)'Y',
    PJMEDIA_FORMAT_UYVY = ((((int)'Y' << 24) | ((int)'V' << 16)) | ((int)'Y' << 8)) | (int)'U',
    PJMEDIA_FORMAT_YVYU = ((((int)'U' << 24) | ((int)'Y' << 16)) | ((int)'V' << 8)) | (int)'Y',
    PJMEDIA_FORMAT_I420 = ((((int)'0' << 24) | ((int)'2' << 16)) | ((int)'4' << 8)) | (int)'I',
    PJMEDIA_FORMAT_IYUV = PJMEDIA_FORMAT_I420,
    PJMEDIA_FORMAT_YV12 = ((((int)'2' << 24) | ((int)'1' << 16)) | ((int)'V' << 8)) | (int)'Y',
    PJMEDIA_FORMAT_I422 = ((((int)'2' << 24) | ((int)'2' << 16)) | ((int)'4' << 8)) | (int)'I',
    PJMEDIA_FORMAT_I420JPEG = ((((int)'0' << 24) | ((int)'2' << 16)) | ((int)'4' << 8)) | (int)'J',
    PJMEDIA_FORMAT_I422JPEG = ((((int)'2' << 24) | ((int)'2' << 16)) | ((int)'4' << 8)) | (int)'J',
    PJMEDIA_FORMAT_H261 = ((((int)'1' << 24) | ((int)'6' << 16)) | ((int)'2' << 8)) | (int)'H',
    PJMEDIA_FORMAT_H263 = ((((int)'3' << 24) | ((int)'6' << 16)) | ((int)'2' << 8)) | (int)'H',
    PJMEDIA_FORMAT_H263P = ((((int)'3' << 24) | ((int)'6' << 16)) | ((int)'2' << 8)) | (int)'P',
    PJMEDIA_FORMAT_H264 = ((((int)'4' << 24) | ((int)'6' << 16)) | ((int)'2' << 8)) | (int)'H',
    PJMEDIA_FORMAT_MJPEG = ((((int)'G' << 24) | ((int)'P' << 16)) | ((int)'J' << 8)) | (int)'M',
    PJMEDIA_FORMAT_MPEG1VIDEO = ((((int)'V' << 24) | ((int)'1' << 16)) | ((int)'P' << 8)) | (int)'M',
    PJMEDIA_FORMAT_MPEG2VIDEO = ((((int)'V' << 24) | ((int)'2' << 16)) | ((int)'P' << 8)) | (int)'M',
    PJMEDIA_FORMAT_MPEG4 = ((((int)'4' << 24) | ((int)'G' << 16)) | ((int)'P' << 8)) | (int)'M'
}
